print("========FANTASY ADVENTURE GENERATOR========")
print()
print()
print()
print()
print()
MythicalCreature = input("What Mythical creature are you? ")
TypeOfBuilding = input("Name a type of building? ")
NameOfPrincess = input("What is the Princess's name? ")
NameOfAnimal = input("Name a type of Animal? ")
NameOfElf = input("What is the name of the elf? ")
NameOfItem = input("What powerful item, will our hero take on his journey? ")
NameOfVillain = input("What is the name of the Antagonist? ")
NameofEvilCastle = input("What is the name of the antagonist's castle? ")
NameOfMinions = input("What is the name of the antagonist's minions? ")
PartOfBody = input("Name a part of body that can wear something? ")
MagicalPower = input("Name something a magical power can do? ")
NormalName = input  ("a normal first name? ")
NameOfMonster = input("Name a type of Monster? ")
print()
print()
print()
print()
print()
print()
print()
print()
print("Once upon a time in a land far away")
print("a young", MythicalCreature, "strolls along the woods towards a", TypeOfBuilding)
print("to see princess", NameOfPrincess,"about a quest")
print("only a brave soul could undertake, whispered by a magical", NameOfAnimal)
print("by a lake one lazy Sunday morning, as he approaches the", TypeOfBuilding)
print("a small elf runs beside, spooking", MythicalCreature)
print("'Hello there, you off to see the princess'?")
print("'Yes i am, i'm going on a quest, if you'd like to come along'")
print("said", MythicalCreature, "'What's your name?'")
print("'My name is,", NameOfElf,"'")
print("he says all excitedly")
print("So off they both go to see the princess")
print("after a while they finally get to the", TypeOfBuilding)
print("Where the princess is waiting")
print("'Come forth travellers, do you seek adventure?'")
print("said the princess")
print("'Yes we do, princess'", NameOfPrincess,"they both bellow excitedly")
print("'I need you to take this powerful'", NameOfItem, "to the magical waterfall")
print("of primera, so that it fortifies our land forever more, but")
print("beware young travellers of an evil force with a desire of self will")
print("that want's the", NameOfItem, "for rule and enslavement over our")
print("land'")
print("'the one that goes by the name of", NameOfVillain,"make sure he does")
print("not get it, so long travellers, wear the", NameOfItem,"for it will")
print("aide you in your travels, now go forth'")
print("with that our heroes journey begins")
print("meanwhile in the dark castle", NameofEvilCastle)
print("the evil", NameOfVillain, "is peering intently at a glowing stone")
print("watching our heroes. 'So they've got the", NameOfItem,"we need to")
print("stop them immediately, that", NameOfItem, "will be mine'")
print("cackles", NameOfVillain, "hysterically")
print("'send", NameOfMinions,"and get me that", NameOfItem,"'")
print("Meanwhile our heroes are walking along the path to adventures, when")
print("suddenly down swoops the", NameOfMinions)
print("'we want that", NameOfItem,"so give it or die'")
print("laughs the leader of the minions")
print("'what are we going to do', says", NameOfElf, "with a quiver")
print("'well, the princess said this", NameOfItem, "will help us, if we wear it,")
print("so here goes', with that the", MythicalCreature, "puts the", NameOfItem)
print("on", PartOfBody,"and points", PartOfBody, "at minions")
print("then Boom!, out comes the", MagicalPower,"and knocks the minions")
print("off through the air and they run away in pain and fear")
print("'Wow well we got rid of them in a hurry', said", NameOfElf)
print("We sure did, says", MythicalCreature)
print("so our heroes continue on the journey. Ahead they see a shiny waterfall")
print("glistening in the sun")
print("'this must be the waterfall of primera', says", NameOfElf)
print("'It is says'", MythicalCreature)
print("As", MythicalCreature, "is about to throw the", NameOfItem,"a loud roar")
print("echoes around then out comes", NameOfMonster)
print("then out of fear", MythicalCreature, "drops the", NameOfItem)
print("and the", NameOfMonster, "swallows it, 'oh not what we gonna do...'")
print("says", MythicalCreature, "just as they fear the worst", NameOfElf)
print("Fires a beam of light from his hatand knocks", NameOfMonster)
print("into the waterfall below")
print("'Wow', said", MythicalCreature,"...but how do we..")
print("then before", MythicalCreature,"can finish, a huge rumble echoes")
print("around the normally dead and stench forest starts to come to life")
print("flowers bloom and birds sing and the sun shines better than it ever has")
print("Our heroes have done it, off they go to the ", TypeOfBuilding,)
print("and see the princess", NameOfPrincess)
print("'well done you have saved our land from slavery, by the way")
print(MythicalCreature,"can i ask you what your real name is?', asks the princess")
print("'Yes, sure it's", NormalName)
print("with that the princess and the land lived happily ever after")
print("========THE END========")
